/*
 * Welcome to the new js2coffee 2.0, now
 * rewritten to use the esprima parser.
 * try it out!
 */
 AccountsTemplates.configure({
  confirmPassword: true,
  enablePasswordChange: true,
  forbidClientAccountCreation: false,
  overrideLoginErrors: true,
  // sendVerificationEmail: true,
  lowercaseUsername: false,
  showAddRemoveServices: true,
  showForgotPasswordLink: true,
  showLabels: true,
  showPlaceholders: true,
  showResendVerificationEmailLink: false,
  continuousValidation: false,
  negativeFeedback: false,
  negativeValidation: true,
  positiveValidation: true,
  positiveFeedback: true,
  showValidating: true,
  // privacyUrl: Config.privacyUrl || null,
  // termsUrl: Config.termsUrl || null,
  // homeRoutePath: Config.dashboardRoute || null,
  onLogoutHook: function() {
    // return myLogout
    // return console.log('logout');
  },
  onSubmitHook: function() {

    // return console.log('submitting form');
  },
 // Texts
 texts: {
  button: {
    signUp: "Join Help Pay Now!",
    changePwd: "Change Help Pay Password",
    enrollAccount: "Enroll Text",
    forgotPwd: "Oops! I Forgot my password",
    resetPwd: "Reset Help Pay password",
    signIn: "Join Help Pay",
  },
  inputIcons: {
    isValidating: "fa fa-spinner fa-spin",
    hasSuccess: "fa fa-check",
    hasError: "fa fa-times",

  },
  socialSignUp: "Register",
  socialIcons: {
    "meteor-developer": "fa fa-rocket"
  },
  title: {
    forgotPwd: "Recover Help Pay Password",
    changePwd: "Change My Help Pay Password",
    enrollAccount: "Enroll Title",
    resetPwd: "Reset Pwd Title",
    signIn: "Help Pay Sign-in",
    signUp: "Help Pay Sign-up",
    verifyEmail: "Verify Email Title",
  },
}
});



// AccountsTemplates.configureRoute('signIn');

// AccountsTemplates.configureRoute('signUp');

// AccountsTemplates.configureRoute('forgotPwd');

// ---
// generated by coffee-script 1.9.2

